version: 2.1
orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            choco install nodejs-lts
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Test and generate coverage report
          command: |
            npm test -- --coverage
      - store_artifacts:
          path: ./coverage/lcov.info
      - run:
          name: Upload coverage report to Coveralls
          command: |
            npx coveralls < ./coverage/lcov.info
