jobs:
  build:
    docker:
      - image: node:16.15.0
    environment: 
      repo_token: oFjecDTIKg0kFeegNobEzH88sB520kKGA
  
    steps:
      - checkout:
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test --coverage
          notify:
      - run:
          name: Upload coverage to Coveralls
          command: npx coveralls < coverage/lcov.info





















    jobs:
  build:
    docker:
      - image: node:18.13.0
    environment:
      COVERALLS_REPO_TOKEN: P3oVZrkN3ro0EWL1sSTkE4OjWrsvruxHq
    working_directory: ~/mybrand/learn-express
    steps:
      - checkout:
          path: ~/mybrand
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test --coverage -- --verbose
      - run:
          name: Upload coverage to Coveralls
          command: npx coveralls < coverage/lcov.info